Deprecate ign_manual_search, ign_create_packages, ign_create_core_library
gazebosim/gz-cmake pull request #255
Opened 2022-05-09 23:01 UTC by chapulina

* Part of https://github.com/gazebo-tooling/release-tools/issues/719
* Broken off https://github.com/gazebosim/gz-cmake/pull/250

## Summary

#250 was getting too large. This PR migrates 3 functions.

Each commit migrates one function.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [x] Updated documentation (as needed)
- [x] Updated migration guide (as needed)
- [x] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

2022-05-12 07:29 UTC, methylDragon commented on cmake/IgnPackaging.cmake
>    # Load platform-specific build hooks if present.
I'm unsure if args need to be bubbled down here to be picked up by `_gz_load_build_hooks`?

2022-05-12 07:30 UTC, methylDragon commented on cmake/IgnPackaging.cmake
>    # Load platform-specific build hooks if present.
Edit: Scratch that, it should be fine because we're using macros

2022-05-12 07:34 UTC, methylDragon requested changes

2022-05-12 07:34 UTC, methylDragon commented on cmake/FindAVDEVICE.cmake
>                      LIBRARY_NAMES "avdevice")
```suggestion
  gz_manual_search(AVDEVICE
                   HEADER_NAMES "libavdevice/avdevice.h"
                   LIBRARY_NAMES "avdevice")
```

2022-05-12 07:34 UTC, methylDragon commented on cmake/FindAVFORMAT.cmake
>                      LIBRARY_NAMES "avformat")
```suggestion
  gz_manual_search(AVFORMAT
                   HEADER_NAMES "libavformat/avformat.h"
                   LIBRARY_NAMES "avformat")
```

2022-05-12 07:34 UTC, methylDragon commented on cmake/FindSWSCALE.cmake
>                      LIBRARY_NAMES "swscale")
```suggestion
  gz_manual_search(SWSCALE
                   HEADER_NAMES "libswscale/swscale.h"
                   LIBRARY_NAMES "swscale")
```

2022-05-12 07:34 UTC, methylDragon commented on cmake/FindUUID.cmake
>                          PATH_SUFFIXES "uuid")
```suggestion
      gz_manual_search(UUID
                       HEADER_NAMES "uuid.h"
                       LIBRARY_NAMES "uuid libuuid"
                       PATH_SUFFIXES "uuid")
```

2022-05-17 19:19 UTC, scpeters approved these changes

2022-05-17 21:58 UTC, merged

2022-07-03 06:41 UTC, scpeters commented on cmake/IgnManualSearch.cmake
> +  gz_manual_search(${PACKAGE_NAME})
hm... I think this should be `${package}` instead of `${PACKAGE_NAME}` (see https://github.com/gazebosim/gz-common/issues/386)