Fix doxygen deprecation warns.
gazebosim/gz-cmake pull request #333
Opened 2023-01-14 17:40 UTC by bperseghetti

Used doxygen -u to fix doxygen warns during colcon builds.

Signed-off-by: Benjamin Perseghetti <bperseghetti@rudislabs.com>

# 🦟 Bug fix

Fixes #332 

Doxygen longer throws deprecation/obsolete warnings.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-01-16 08:50 UTC, ahcorde approved these changes

2023-01-18 02:45 UTC, azeey requested changes
Some of the newly added parameters cause warnings on Ubuntu 20.04:

```
warning: ignoring unsupported tag 'PYTHON_DOCSTRING' at line 226, file /home/addisu/ws/garden/build/gz-math7/api.dox
warning: ignoring unsupported tag 'NUM_PROC_THREADS' at line 464, file /home/addisu/ws/garden/build/gz-math7/api.dox
warning: ignoring unsupported tag 'RESOLVE_UNNAMED_PARAMS' at line 534, file /home/addisu/ws/garden/build/gz-math7/api.dox
warning: ignoring unsupported tag 'CLANG_ADD_INC_PATHS' at line 1122, file /home/addisu/ws/garden/build/gz-math7/api.dox
warning: ignoring unsupported tag 'HTML_FORMULA_FORMAT' at line 1575, file /home/addisu/ws/garden/build/gz-math7/api.dox
warning: ignoring unsupported tag 'DOT_UML_DETAILS' at line 2405, file /home/addisu/ws/garden/build/gz-math7/api.dox
warning: ignoring unsupported tag 'DOT_WRAP_THRESHOLD' at line 2414, file /home/addisu/ws/garden/build/gz-math7/api.dox
```
I think it would be safe to just remove those parameters and let doxygen use the defaults.

2023-01-23 14:55 UTC, bperseghetti commented
> 

I should mention I only ran this on 22.04. And it was to fix the colcon bugs/errors that I was getting from deprecation warns.

2023-01-23 15:07 UTC, bperseghetti commented
@azeey should this be focused/targeted for only 22.04 forward or does gz-cmake3 also apply to 20.04 as well?
Would a gz-camke4 make sense if there are enough difference between doxygen on 22.04 and 20.04?

2023-04-10 21:00 UTC, bperseghetti commented
@azeey seems to now fix my warn/errors in 22.04. Just removed `COLS_IN_ALPHA_INDEX` and `TCL_SUBST`

2023-04-14 21:57 UTC, azeey approved these changes

2023-04-14 21:57 UTC, merged